apiVersion: ray.io/v1
kind: RayJob
metadata:
  name: multimodel-batch-inference
  namespace: ray
spec:
  entrypoint: python /home/ray/scripts/main.py
  runtimeEnvYAML: |
    pip:
      - ipywidgets==8.1.3
      - matplotlib==3.10.0
      - mlflow==2.19.0
      - torch==2.7.1
      - transformers==4.52.3
      - scikit-learn==1.6.0
      - "doggos @ git+https://github.com/anyscale/multimodal-ai.git#subdirectory=doggos"
    env_vars:
      BATCH_SIZE: "64"
      NUM_GPU_ACTORS: "2"
      TOP_K: "5"

  shutdownAfterJobFinishes: false   # keep cluster alive to inspect results

  submitterPodTemplate:
    spec:
      restartPolicy: Never
      containers:
        - name: ray-job-submitter
          image: rayproject/ray:2.48.0-py312

  rayClusterSpec:
    rayVersion: "2.48.0"
    enableInTreeAutoscaling: false

    headGroupSpec:
      rayStartParams:
        num-cpus: "0"
        dashboard-host: "0.0.0.0"
        disable-usage-stats: "true"
      template:
        spec:
          containers:
            - name: ray-head
              image: rayproject/ray:2.48.0-py312
              env:
                - name: RAY_DISABLE_DOCKER_CPU_WARNING
                  value: "1"
                - name: RAY_SCHEDULER_EVENTS
                  value: "0"
              ports:
                - containerPort: 6379
                  name: gcs-server
                - containerPort: 8265
                  name: dashboard
                - containerPort: 10001
                  name: client
              resources:
                limits:
                  cpu: "4"
                  memory: "16Gi"
                requests:
                  cpu: "4"
                  memory: "16Gi"
              volumeMounts:
                - name: scripts
                  mountPath: /home/ray/scripts
          volumes:
            - name: scripts
              configMap:
                name: multimodel-batch-inference-scripts
                items:
                  - key: main.py
                    path: main.py

    workerGroupSpecs:
      - groupName: gpu-workers
        replicas: 2
        minReplicas: 2
        maxReplicas: 2
        rayStartParams:
          num-gpus: "1"
          num-cpus: "8"
        template:
          spec:
            containers:
              - name: ray-worker
                image: rayproject/ray:2.48.0-py312-gpu
                resources:
                  limits:
                    cpu: "8"
                    memory: "16Gi"
                    nvidia.com/gpu: "1"
                  requests:
                    cpu: "8"
                    memory: "16Gi"
                    nvidia.com/gpu: "1"
                volumeMounts:
                  - name: scripts
                    mountPath: /home/ray/scripts
            volumes:
              - name: scripts
                configMap:
                  name: multimodel-batch-inference-scripts
                  items:
                    - key: main.py
                      path: main.py
