apiVersion: flex.aks.azure.com/v1alpha1
kind: NebiusNodeClass
metadata:
  name: nebius
spec:
  projectID: "project-e00hks1mpr00yvvfrmcvbp"
  region: "eu-north1"
  subnetID: "vpcsubnet-e00kh7b88dkz0nbmzv"
  osDiskSizeGB: 128
  wireguardPeerCIDR: "100.96.1.0/24"