apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: nebius-gpu-nodepool
spec:
  template:
    metadata:
      labels:
        nodepool: nebius-gpu-nodepool
        nvidia.com/gpu.present: "true"
    spec:
      nodeClassRef:
        group: flex.aks.azure.com
        kind: NebiusNodeClass
        name: nebius
      startupTaints:
        - key: nvidia.com/gpu
          value: "not-ready"
          effect: NoSchedule
        - key: node.cilium.io/agent-not-ready
          value: "true"
          effect: NoSchedule
      requirements:
        - key: node.kubernetes.io/instance-type
          operator: In
          values:
            - gpu-h100-sxm-1gpu-16vcpu-200gb
  limits:
    cpu: "1000"
    memory: 10000Gi
    nvidia.com/gpu: "64"
