apiVersion: v1
kind: PersistentVolume
metadata:
  name: s3-pv
spec:
  capacity:
    storage: 1000Gi
  accessModes:
    - ReadWriteMany
  storageClassName: "s3"
  claimRef:
    namespace: ray
    name: cluster-storage
  mountOptions:
    - allow-delete
    - allow-overwrite
    - region us-east-2
    - --no-sign-request
  csi:
    driver: s3.csi.aws.com
    volumeHandle: s3-csi-driver-volume
    volumeAttributes:
      bucketName: "your-s3-bucket-name"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cluster-storage
  namespace: ray
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: "s3"
  resources:
    requests:
      storage: 100Gi
  volumeName: s3-pv
